// Code generated by Axiom CLI; DO NOT EDIT.
namespace Axiom;

using System.Collections.Generic;

/// <summary>
/// IAxiomContext — the single injection point for platform capabilities (ADR-001).
///
/// <para>A node receives one IAxiomContext per invocation and reaches every
/// platform capability through it:</para>
/// <code>
///   var (key, found) = ax.Secrets().Get("OPENAI_KEY");
///   var nodes        = ax.Reflection().Flow().Nodes();
/// </code>
///
/// <para>Node code never talks to the platform directly — capabilities are
/// consolidated here to prevent signature drift across SDK versions (ADR-001).
/// All capability types are nested so the whole contract lives in one file, and
/// the logger interface is nested (IAxiomContext.ILogger) so it never collides
/// with Microsoft.Extensions.Logging.ILogger when both namespaces are in scope.</para>
/// </summary>
public interface IAxiomContext
{
    ILogger Log();

    ISecrets Secrets();

    string ExecutionId();

    string FlowId();

    string TenantId();

    IReflection Reflection();

    IMutation Mutation();

    // ── Logging & secrets ───────────────────────────────────────────────────

    /// <summary>Structured logger pre-configured for a single node invocation.</summary>
    public interface ILogger
    {
        void Debug(string msg, IDictionary<string, string>? attrs = null);
        void Info(string msg, IDictionary<string, string>? attrs = null);
        void Warn(string msg, IDictionary<string, string>? attrs = null);
        void Error(string msg, IDictionary<string, string>? attrs = null);
    }

    /// <summary>
    /// Typed result of <see cref="ISecrets.Status"/> — ADR-156.
    ///
    /// <para><c>Get(name)</c> alone returns <c>("", false)</c> both when a
    /// secret was revoked after execution start and when it was never
    /// configured at all — a node cannot tell "re-authorize this
    /// credential" from "check axiom.yaml" from that result alone. Use
    /// <c>Status()</c> when the distinction matters.</para>
    /// </summary>
    public enum SecretStatus
    {
        /// <summary>The secret currently resolves to a value; Get(name) returns it.</summary>
        Available,
        /// <summary>The secret existed in this execution's initial snapshot but no
        /// longer resolves against the live vault — it was deleted or revoked
        /// after the execution started. Get(name) returns ("", false).</summary>
        Revoked,
        /// <summary>The secret was never present for this node — never configured
        /// by the tenant, or (for a non-owned node) not authorized. Get(name)
        /// returns ("", false), identically to Revoked.</summary>
        Unset,
    }

    /// <summary>Read-only access to tenant secrets resolved by the platform.</summary>
    public interface ISecrets
    {
        /// <summary>Returns (value, true) when the named secret is present, else ("", false).</summary>
        (string Value, bool Found) Get(string name);

        /// <summary>Returns the typed status of a declared secret — ADR-156.
        /// Distinguishes SecretStatus.Revoked (declared, existed at
        /// execution start, no longer resolvable) from SecretStatus.Unset
        /// (never configured) — a distinction Get alone cannot make since
        /// both return ("", false).
        ///
        /// ADR-156 (2026-07-20): a DEFAULT interface method, not an abstract
        /// one, so the accessor stays BACKWARD-COMPATIBLE — an abstract member
        /// would break every existing node's hand-written ISecrets test double
        /// at compile time. The platform's MapSecrets overrides it with the
        /// real Available/Revoked/Unset distinction; an implementer that only
        /// provides Get inherits this default (Available when present, else
        /// Unset), never a false Revoked.</summary>
        SecretStatus Status(string name) => Get(name).Found ? SecretStatus.Available : SecretStatus.Unset;
    }

    // ADR-129 (2026-07-11): agentic memory (ax.Agent().Memory()) is out of
    // scope for beta and has been removed from the node SDK entirely — a
    // shared marketplace node's memory proxy stamped the deploy-time
    // publisher tenant, letting unrelated tenants composing the same node
    // read each other's memory. Removing the client surface here closes the
    // reachable path at compile time. The backend (internal/memory,
    // proto/memory, MemoryService) is retained for post-beta.

    // ── Flow reflection (ADR-050 / ADR-055) ─────────────────────────────────

    /// <summary>A node in the running flow graph. GridCol/GridRow are the
    /// ADR-086 coarse-grid cell (column = flow depth, row = parallel lane).</summary>
    public record ReflectionNode(
        int InstanceId, string NodeUlid, string Name, string PackageName,
        string PackageVersion, string NodeType, string InputMessageName,
        string OutputMessageName, string CanvasNodeId, int GridCol, int GridRow);

    /// <summary>ADR-055 / GAP-4: agent-readable digest of an edge's dispatch condition.</summary>
    public record ConditionSummary(string Field, string Op, IReadOnlyList<string> Operands);

    /// <summary>An edge in the running flow graph. ConditionSummary is null when the edge is unconditional.</summary>
    public record ReflectionEdge(
        int SrcInstance, int DstInstance, string CanvasEdgeId, bool HasCondition,
        bool HasAdapter, int MaxIterations, ConditionSummary? ConditionSummary);

    /// <summary>The executing position within the (possibly nested) flow.</summary>
    public record FlowPosition(
        int CurrentInstance, int Depth, IReadOnlyDictionary<int, int> LoopIterations,
        IReadOnlyList<string> SubflowStackGraphIds);

    /// <summary>Read-only view of the running flow graph.</summary>
    public interface IFlowReflection
    {
        IReadOnlyList<ReflectionNode> Nodes();
        IReadOnlyList<ReflectionEdge> Edges();
        IReadOnlyList<ReflectionEdge> LoopEdges();
        FlowPosition Position();
        string GraphId();
    }

    public interface IReflection
    {
        IFlowReflection Flow();
    }

    // ── Flow mutation (ADR-051 / ADR-054) ───────────────────────────────────

    /// <summary>Canvas placement for a mutation-added node. ADR-086: set
    /// GridCol/GridRow to place at a coarse-grid cell (the worker derives
    /// pixels; grid takes precedence over X/Y).</summary>
    public record CanvasPosition(double X, double Y, int GridCol, int GridRow)
    {
        /// <summary>Pixel-only convenience; grid cell defaults to (0,0).</summary>
        public CanvasPosition(double x, double y) : this(x, y, 0, 0) { }
    }

    /// <summary>ADR-054: a conditional dispatch for a mutation-added edge.</summary>
    public record EdgeCondition(string Op, string Field, string Value);

    /// <summary>Buffered, additive mutation of the running flow graph.</summary>
    public interface IFlowMutation
    {
        int AddNode(string packageName, string packageVersion, CanvasPosition? canvasPosition);
        void AddEdge(int srcInstance, int dstInstance, EdgeCondition? condition);
    }

    public interface IMutation
    {
        IFlowMutation Flow();
    }

    // ── Node telemetry (ADR-073) ────────────────────────────────────────────
    // ADR-073 (2026-06-09): tenant-safe telemetry surface. Node code records
    // events/metrics here; the items are buffered in-process and flushed onto
    // NodeResponse.telemetry, where the SIDECAR re-emits them through its own
    // trusted providers (parented under node.invoke, stamped with the
    // authoritative tenant_id). The node never reaches the collector — that is
    // the trust boundary (CLAUDE.md rule #2). Secret-keyed attributes are dropped
    // at the sidecar. Under `axiom dev` (no sidecar) it degrades to a no-op,
    // exactly like Log().

    /// <summary>The tenant-safe node telemetry surface (ADR-073).</summary>
    public interface ITelemetry
    {
        /// <summary>Record a named event (duration-less span event) on the node's
        /// invocation span. Optional attributes are forwarded as typed values.</summary>
        void AddEvent(string name, IDictionary<string, string>? attrs = null);

        /// <summary>Add <paramref name="value"/> to a named custom counter.</summary>
        void Counter(string name, double value, IDictionary<string, string>? attrs = null);

        /// <summary>Record <paramref name="value"/> on a named custom histogram.</summary>
        void Histogram(string name, double value, IDictionary<string, string>? attrs = null);
    }
}

/// <summary>
/// Telemetry accessor (ADR-073). Deliberately a static helper rather than a
/// method on <see cref="IAxiomContext"/>: adding a member to the public context
/// interface would break every package's committed test doubles (the durable-test
/// re-push regression). In production the concrete context implements the internal
/// carrier so this reaches the per-invocation buffer; under `axiom dev` / unit
/// tests it returns a no-op, exactly like the dev logger.
///
/// <code>
///   Axiom.Telemetry.Of(ax).AddEvent("cache_hit");
/// </code>
/// </summary>
public static class Telemetry
{
    public static IAxiomContext.ITelemetry Of(IAxiomContext ax) =>
        ax is ITelemetryCarrier c ? c.AxiomTelemetry() : NoopTelemetry.Instance;
}

/// <summary>Implemented by the production AxiomContext so <see cref="Telemetry.Of"/>
/// can reach the per-invocation buffer without touching the public context
/// interface. Internal on purpose — node code and test doubles never see it.</summary>
internal interface ITelemetryCarrier
{
    IAxiomContext.ITelemetry AxiomTelemetry();
}

/// <summary>No-op telemetry used under `axiom dev` and in unit tests (no sidecar
/// to flush onto). Mirrors the no-op dev logger behaviour.</summary>
internal sealed class NoopTelemetry : IAxiomContext.ITelemetry
{
    public static readonly NoopTelemetry Instance = new();
    public void AddEvent(string name, IDictionary<string, string>? attrs = null) {}
    public void Counter(string name, double value, IDictionary<string, string>? attrs = null) {}
    public void Histogram(string name, double value, IDictionary<string, string>? attrs = null) {}
}
